import type {
  CatalogProduct,
  FeaturedProductSystem,
  ProductCategory,
} from "@/types";

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  { slug: "all", label: "All" },
  { slug: "fire-detection", label: "Fire Detection" },
  { slug: "telephone", label: "Telephone Systems" },
  { slug: "public-address", label: "Public Address" },
  { slug: "general-alarm", label: "General Alarm" },
  { slug: "telegraph", label: "Engine Telegraph" },
  { slug: "navigation", label: "Navigation & Lighting" },
  { slug: "instrumentation", label: "Instrumentation" },
  { slug: "alarm-signaling", label: "Alarm & Signaling" },
];

export const FEATURED_PRODUCT_SYSTEMS: FeaturedProductSystem[] = [
  {
    id: "fdas",
    acronym: "FDAS",
    title: "Fire Detection and Alarm System",
    description:
      "Controllers, detectors, manual call points, and audio-visual sirens for class-compliant vessel fire safety.",
    imageSrc: "/images/products/product-36.png",
    imageAlt:
      "Lanoso Corporation fire detection and alarm system product lineup.",
  },
  {
    id: "mats",
    acronym: "MATS",
    title: "Marine Automatic Telephone System",
    description:
      "Exchange units, rugged wall stations, desk phones, and high-noise headsets for shipboard communications.",
    imageSrc: "/images/products/product-46.png",
    imageAlt:
      "Lanoso Corporation marine automatic telephone system components.",
  },
  {
    id: "pas",
    acronym: "PAS",
    title: "Public Address System",
    description:
      "Main units, remote stations, amplifiers, and zone paging for bridge, deck, engine room, and accommodation.",
    imageSrc: "/images/products/product-25.png",
    imageAlt: "Lanoso Corporation public address system equipment.",
  },
  {
    id: "gas",
    acronym: "GAS",
    title: "General Alarm System",
    description:
      "Emergency alarm controllers, visual signals, and manual call points for vessel-wide alerting.",
    imageSrc: "/images/products/product-14.png",
    imageAlt: "Lanoso Corporation general alarm system hardware.",
  },
  {
    id: "battery-less-phone",
    acronym: "BLT",
    title: "Battery-Less Telephone",
    description:
      "Sound-powered hand-crank stations for emergency communication when ship power is unavailable.",
    imageSrc: "/images/products/product-16.png",
    imageAlt: "Lanoso Corporation battery-less marine telephone system.",
  },
];

const img = (n: number) => `/images/products/product-${String(n).padStart(2, "0")}.png`;

/** Equipment and panels Lanoso supplies, installs, and services. */
export const CATALOG_PRODUCTS: CatalogProduct[] = [
  {
    id: "p01",
    title: "Marine Smoke / Heat Detector",
    manufacturer: "Fucheng",
    category: "fire-detection",
    imageSrc: img(1),
    imageAlt: "Marine-certified smoke or heat detector with ship inspection markings.",
  },
  {
    id: "p02",
    title: "Batteryless Telephone HSC-12J",
    manufacturer: "Hailun",
    category: "telephone",
    imageSrc: img(2),
    imageAlt: "Sound-powered batteryless telephone with headset for marine use.",
  },
  {
    id: "p03",
    title: "Rudder Angle Indicator (Panoramic)",
    category: "instrumentation",
    imageSrc: img(3),
    imageAlt: "Three-face rudder angle indicator for bridge mounting.",
  },
  {
    id: "p04",
    title: "Marine Electric Horn",
    category: "alarm-signaling",
    imageSrc: img(4),
    imageAlt: "Heavy-duty electric ship horn for navigation and signaling.",
  },
  {
    id: "p05",
    title: "Marine Alarm Siren / Horn Speaker",
    category: "alarm-signaling",
    imageSrc: img(5),
    imageAlt: "Weatherproof marine alarm horn speaker on junction box.",
  },
  {
    id: "p06",
    title: "General Alarm Controller Panel",
    manufacturer: "Haihsea",
    category: "general-alarm",
    imageSrc: img(6),
    imageAlt: "Marine general alarm controller with indicator lights and controls.",
  },
  {
    id: "p07",
    title: "Manual Alarm Call Point",
    manufacturer: "Haihsea",
    category: "general-alarm",
    imageSrc: img(7),
    imageAlt: "Marine manual alarm call point with horn symbol.",
  },
  {
    id: "p08",
    title: "Public Address Remote Station",
    manufacturer: "Haihsea",
    category: "public-address",
    imageSrc: img(8),
    imageAlt: "Wall-mounted public address remote with handheld microphone.",
  },
  {
    id: "p09",
    title: "PA System Amplifier Unit",
    category: "public-address",
    imageSrc: img(9),
    imageAlt: "Rack-mount public address amplifier with microphone.",
  },
  {
    id: "p10",
    title: "Electric Horn (24V DC)",
    manufacturer: "Nanjing Zehai",
    category: "alarm-signaling",
    imageSrc: img(10),
    imageAlt: "24V DC marine electric horn rated 110 dB.",
  },
  {
    id: "p11",
    title: "Navigation Light Control Panel",
    manufacturer: "Haihsea",
    category: "navigation",
    imageSrc: img(11),
    imageAlt: "Navigation light unit panel with ship diagram and zone controls.",
  },
  {
    id: "p12",
    title: "Engine Room Alarm Indicator Panel",
    category: "alarm-signaling",
    imageSrc: img(12),
    imageAlt: "Engine room alarm indicator panel with status LEDs.",
  },
  {
    id: "p13",
    title: "Marine Sound & Light Alarm (Dual Unit)",
    manufacturer: "Jietai",
    category: "alarm-signaling",
    imageSrc: img(13),
    imageAlt: "Pair of marine high-power sound and light alarm units.",
  },
  {
    id: "p15",
    title: "Fire Alarm Control Panel",
    manufacturer: "JBS",
    category: "fire-detection",
    imageSrc: img(15),
    imageAlt: "JBS fire alarm controller with keypad and zone indicators.",
  },
  {
    id: "p17",
    title: "Navigation Light Unit",
    manufacturer: "Haihsea",
    category: "navigation",
    imageSrc: img(17),
    imageAlt: "Haihsea navigation light unit with ship lighting diagram.",
  },
  {
    id: "p18",
    title: "Audio-Visual Fire Siren",
    manufacturer: "Fucheng",
    category: "fire-detection",
    imageSrc: img(18),
    imageAlt: "Fucheng audio and visual fire alarm siren with red dome.",
  },
  {
    id: "p19",
    title: "Manual Fire Call Point",
    manufacturer: "Fucheng",
    category: "fire-detection",
    imageSrc: img(19),
    imageAlt: "Fucheng manual fire call point break-glass station.",
  },
  {
    id: "p20",
    title: "Digital Rudder Angle Indicator",
    manufacturer: "Haihsea",
    category: "instrumentation",
    imageSrc: img(20),
    imageAlt: "Haihsea digital rudder angle indicator with port and starboard scale.",
  },
  {
    id: "p21",
    title: "Public Address Remote Station RM-1G",
    manufacturer: "Haihsea",
    category: "public-address",
    imageSrc: img(21),
    imageAlt: "RM-1G public address remote station with zone selection buttons.",
  },
  {
    id: "p22",
    title: "PA Main Unit (Panel Mount)",
    category: "public-address",
    imageSrc: img(22),
    imageAlt: "Panel-mount public address main unit with PTT microphone.",
  },
  {
    id: "p23",
    title: "Circular Fire Alarm Siren",
    category: "fire-detection",
    imageSrc: img(23),
    imageAlt: "Red circular marine fire alarm siren.",
  },
  {
    id: "p24",
    title: "Combined Audio-Visual Alarm",
    category: "alarm-signaling",
    imageSrc: img(24),
    imageAlt: "Combined marine strobe and siren alarm unit IP56 rated.",
  },
  {
    id: "p26",
    title: "Fire Alarm Controller JBS-MB",
    manufacturer: "Haihsea / JBS",
    category: "fire-detection",
    imageSrc: img(26),
    imageAlt: "JBS-MB marine fire alarm controller with LCD and zone LEDs.",
  },
  {
    id: "p27",
    title: "Main Engine Telegraph Transmitter CL1-T",
    manufacturer: "Fucheng",
    category: "telegraph",
    imageSrc: img(27),
    imageAlt: "CL1-T main engine telegraph transmitter with ahead and astern commands.",
  },
  {
    id: "p28",
    title: "Emergency Telegraph Repeater",
    manufacturer: "Nanjing Zehai",
    category: "telegraph",
    imageSrc: img(28),
    imageAlt: "Emergency main engine telegraph repeater panel.",
  },
  {
    id: "p29",
    title: "Fire Alarm Controller JBS-MA",
    manufacturer: "Haihsea",
    category: "fire-detection",
    imageSrc: img(29),
    imageAlt: "JBS-MA fire alarm controller with LCD status display.",
  },
  {
    id: "p30",
    title: "Engineer Alarm Main Unit",
    manufacturer: "Nanjing Zehai",
    category: "alarm-signaling",
    imageSrc: img(30),
    imageAlt: "Engineer alarm main unit with microphone and indicator columns.",
  },
  {
    id: "p31",
    title: "HKD Public Address Main Unit",
    manufacturer: "Haihsea",
    category: "public-address",
    imageSrc: img(31),
    imageAlt: "Haihsea HKD public address main unit with digital audio player.",
  },
  {
    id: "p32",
    title: "General Emergency Alarm Controller RM-1B",
    category: "general-alarm",
    imageSrc: img(32),
    imageAlt: "General emergency alarm controller with manual alarm button.",
  },
  {
    id: "p33",
    title: "Visual Alarm Signal (Amber Dome)",
    category: "general-alarm",
    imageSrc: img(33),
    imageAlt: "Marine visual alarm with amber dome light.",
  },
  {
    id: "p34",
    title: "Vessel General Alarm Push Station",
    category: "general-alarm",
    imageSrc: img(34),
    imageAlt: "Marine general alarm push station with vessel icon.",
  },
  {
    id: "p35",
    title: "Automatic Telephone HAC-100G/P",
    manufacturer: "Lanoso / Fucheng",
    category: "telephone",
    imageSrc: img(35),
    imageAlt: "Lanoso automatic marine telephone HAC-100G/P wall unit.",
  },
  {
    id: "p37",
    title: "Alarm Remote Station RM-1A",
    manufacturer: "Nanjing Zehai",
    category: "alarm-signaling",
    imageSrc: img(37),
    imageAlt: "RM-1A alarm remote station with general emergency alarm button.",
  },
  {
    id: "p38",
    title: "Fire Detection Loop Interface Module",
    category: "fire-detection",
    imageSrc: img(38),
    imageAlt: "Marine fire detection wiring interface module.",
  },
  {
    id: "p39",
    title: "Alarm Main Unit with PTT Microphone",
    manufacturer: "Nanjing Zehai",
    category: "alarm-signaling",
    imageSrc: img(39),
    imageAlt: "Alarm main unit with ABCO push-to-talk microphone.",
  },
  {
    id: "p40",
    title: "Engine Telegraph Receiver Panel",
    category: "telegraph",
    imageSrc: img(40),
    imageAlt: "Main engine telegraph receiver or repeater control panel.",
  },
  {
    id: "p41",
    title: "Marine Intercom Control Module",
    category: "public-address",
    imageSrc: img(41),
    imageAlt: "Marine intercom or PA control module for bulkhead mounting.",
  },
  {
    id: "p42",
    title: "Telegraph Command Display Unit",
    category: "telegraph",
    imageSrc: img(42),
    imageAlt: "Engine room telegraph command display unit.",
  },
  {
    id: "p43",
    title: "High-Power Sound & Light Alarm YMC-T",
    manufacturer: "Jietai",
    category: "alarm-signaling",
    imageSrc: img(43),
    imageAlt: "120W marine sound and light alarm IP56 rated.",
  },
  {
    id: "p44",
    title: "Strobe & Siren Combination Unit",
    category: "alarm-signaling",
    imageSrc: img(44),
    imageAlt: "Combined red strobe and siren marine alarm unit.",
  },
  {
    id: "p45",
    title: "Fire Alarm Zone Monitor Panel",
    category: "fire-detection",
    imageSrc: img(45),
    imageAlt: "Fire alarm zone monitoring panel with status indicators.",
  },
];

export function getProductsByCategory(
  category: ProductCategorySlug,
): CatalogProduct[] {
  if (category === "all") return CATALOG_PRODUCTS;
  return CATALOG_PRODUCTS.filter((p) => p.category === category);
}
